[tool.poetry]
name = "3D Env Model"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
tensorflow = "^2.18.1"
numpy = "2.3.2"
poetry-core = ">=1.4.0"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"
