[package]
name = "Drone"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1" }
bevy_rapier3d = { version = "0.30.0", features = ["dim3", "debug-render"] }
bevy_math = "0.16.1"